<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ICT-2003278-AQA" ignored="0" name="Login2" tests="1" failures="0" timestamp="07 Mar 2023 11:52:25 GMT" time="61.843" errors="0">
  <testcase name="@BeforeMethod beforeMethod" time="61.832" classname="wrappers.KMA">
    <failure type="java.lang.RuntimeException" message="FAILED">
      <![CDATA[java.lang.RuntimeException: FAILED
at utils.Reporter.reportStep(Reporter.java:34)
at utils.Reporter.reportStep(Reporter.java:44)
at wrappers.BaseClass.invokeApp(BaseClass.java:105)
at wrappers.BaseClass.invokeApp(BaseClass.java:72)
at wrappers.KMA.beforeMethod(KMA.java:35)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod beforeMethod -->
  <testcase name="@AfterMethod afterMethod" time="0.0" classname="wrappers.KMA">
    <skipped/>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase name="createAccount" time="0.0" classname="testcases.TC001_2_CA_5440910">
    <skipped/>
  </testcase> <!-- createAccount -->
</testsuite> <!-- Login2 -->
